---
extends: default
rules:
  comments:
    ignore: |
      templates/*/cloud-config.yaml
  document-start: disable  # Adding document separators to inline YAML breaks runtime-init
  line-length:
    max: 120
